# Generated by Django 2.2.1 on 2019-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('ns_category_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('job_type_id', models.IntegerField()),
                ('job_title', models.TextField(blank=True, null=True)),
                ('job_slug', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_image', models.TextField(blank=True, null=True)),
                ('job_status', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('House_of', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.CharField(blank=True, max_length=4, null=True)),
                ('epaperlink', models.TextField(blank=True, null=True)),
                ('imagelink', models.TextField(blank=True, null=True)),
                ('imagelinkautogenerate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
