# Generated by Django 2.2.1 on 2019-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Year',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
