# Generated by Django 2.2.1 on 2019-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190602_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='House_of',
            new_name='houseof',
        ),
    ]
