# Generated by Django 2.2.1 on 2019-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190604_2332'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['job_title'], name='jobtitle_idx', opclasses=['text_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['location'], name='location_idx', opclasses=['bpchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['houseof'], name='houseof_idx', opclasses=['bpchar_pattern_ops']),
        ),
    ]
